### ISSUE TITLE
How to proceed with vbuild after being inactive for years?

### ISSUE THREAD

**Issue by falkoschindler** [manatlan/vbuild#11]
First things first: vbuild is a great project, doing one thing very well. Our own project [NiceGUI](https://github.com/zauberzeug/nicegui) uses it internally to convert SFCs to HTML/JavaScript/CSS.

Only recently we noticed a few bugs that we would love to see fixed. Especially for the deprecation warning https://github.com/manatlan/vbuild/issues/10 there's already a pull request https://github.com/manatlan/vbuild/pull/9.

Now I'm thinking about copying the code into our own project or forking the whole repo. But, to make bugfixes available to the community, we would need to release a separate PyPI package as a successor to vbuild. Maybe it's better to "take over" this repo and continue developing the existing package. I'm just not sure if my team and I would be a good fit, since some of the current issues require quite some deep knowledge of Vue and JS, which we might be lacking.

@manatlan What's your thought on this?

And is there anyone interested in actively supporting this project?

**Comment by manatlan** [comment]
Hi @falkoschindler ...
I didn't see that before today ... sorry for that !

I did'nt know that vbuild was still used ... and I pretty proud that nicegui use it, for sure !
NiceGUI is a really good project ! But theses last days/year ... I'm really concentrated on [htag](https://github.com/manatlan/htag), which could be seen as a nicegui competitor.

But I promess you, that I will do my best to update vbuild ! (but not for the next 2weeks)
Because we've got the same goal (python only!)

**Comment by manatlan** [comment]
hi @falkoschindler ...
I've setuped this repo, to use the ci/cd github actions (like all my new projects), it will be faster/easier for futurs fixes. And released a 0.8.2, with the pr#9 !
Tell me If it's good for you

**Comment by falkoschindler** [comment]
Thanks a lot, @manatlan!
I'm very happy to see PR #9 being merged and version 0.8.2 being released!
This answers my question about the future of vbuild: You're still committed to at least merge PRs now and then. 🙂
So I'll close this issue as resolved. Thanks!
